# Generated by Django 3.2.4 on 2021-08-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='is_feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='column',
            name='use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factory',
            name='parsed_training_set',
            field=models.FileField(blank=True, null=True, upload_to='intermediate'),
        ),
        migrations.AddField(
            model_name='factory',
            name='processed_training_set',
            field=models.FileField(blank=True, null=True, upload_to='intermediate'),
        ),
        migrations.AlterField(
            model_name='column',
            name='belong_transaction',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='diff',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='column',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='column',
            name='is_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='column',
            name='is_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='column',
            name='log',
            field=models.BooleanField(default=False),
        ),
    ]
