# Generated by Django 3.2.4 on 2021-08-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_auto_20210821_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='fill_na_avg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factory',
            name='normalizers',
            field=models.FileField(blank=True, null=True, upload_to='models'),
        ),
    ]
