# Generated by Django 3.2.4 on 2021-08-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_auto_20210822_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='config',
            field=models.TextField(default='{}'),
        ),
    ]
