# Generated by Django 3.2.4 on 2021-08-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_remove_factory_processed_training_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factory',
            old_name='model',
            new_name='model_0',
        ),
    ]
