# Generated by Django 3.2.4 on 2021-08-23 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payingmethod_prestige_websitemanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='prestige',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='plan',
        ),
        migrations.AddField(
            model_name='prestige',
            name='expired_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prestige',
            name='max_existed_factory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prestige',
            name='training_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
