# Generated by Django 3.2.4 on 2021-08-23 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_prestige_expired_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestige',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='prestige',
            name='expired_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
