# Generated by Django 3.2.4 on 2021-09-01 12:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_manager', '0007_rename_model_factory_model_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('predicting_set', models.FileField(upload_to='data')),
                ('transaction_sheet', models.TextField(blank=True)),
                ('parsed_predicting_set', models.FileField(upload_to='intermediate')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.factory')),
            ],
        ),
    ]
