# Generated by Django 3.2.4 on 2021-09-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_runtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='parsed_predicting_set',
            field=models.FileField(blank=True, null=True, upload_to='intermediate'),
        ),
    ]
