# Generated by Django 3.2.4 on 2021-09-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_runtime', '0003_predict_prediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predict',
            name='transaction_sheet',
        ),
        migrations.AddField(
            model_name='predict',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
